# push to develop branch or push a tag starting with 'v' to trigger a pipeline
trigger:
  - develop
  - refs/tags/v*

variables:
  - group: Github
  # (de)activate stages
  - name: BUILD
    value: true
  - name: DEPLOY
    value: true
  # (de)activate operating systems
  - name: LINUX
    value: true
  - name: WINDOWS
    value: true
  - name: MAC
    value: true
  - name: QT_VERSION
    value: '5.15.1'

stages:
- stage: build
  condition: eq(variables.BUILD, true)
  jobs:

  # BUILD for LINUX (Qt 5.15.0)
  - job: linux
    condition: eq(variables.LINUX, true)
    pool:
      vmImage: 'ubuntu-16.04'
    variables:
      target: 'release' # default target
    steps:
    - script: |
        sudo add-apt-repository ppa:beineri/opt-qt-5.15.0-xenial
        sudo apt-get update
        sudo apt-get -y install qt515-meta-full
        sudo apt-get -y install qt5-qmake
        sudo apt-get -y install libgl1-mesa-dev
        curl -Lo linuxdeployqt https://github.com/probonopd/linuxdeployqt/releases/download/6/linuxdeployqt-6-x86_64.AppImage
        chmod a+x linuxdeployqt
      displayName: 'setup'
    - script: echo "##vso[task.setvariable variable=target;]debug"
      condition: not(contains(variables['Build.SourceBranch'], 'refs/tags/v')) # build with debug output unless it's a v* tag
    - script: |
        source /opt/qt515/bin/qt515-env.sh
        rm -rf build/ && mkdir build && cd build
        qmake ../src/QRoboticsCenter/QRoboticsCenter.pro
        if [ $(target) = 'debug' ]; then make debug -j5; else make -j5; fi
      displayName: 'build'
    - script: |
        source /opt/qt515/bin/qt515-env.sh
        python3 resources/scripts/prepare_linuxdeploy.py
        cp linuxdeployqt build/linuxdeployqt && cd build
        cp ../src/QRoboticsCenter/icons/QRoboticsCenter_logo.png app/usr/share/icons/hicolor/256x256/QRoboticsCenter.png
        cp bin/QRoboticsCenter app/usr/bin/QRoboticsCenter
        ./linuxdeployqt app/usr/share/applications/QRoboticsCenter.desktop -unsupported-allow-new-glibc -appimage
        mv QRoboticsCenter-*-x86_64.AppImage QRoboticsCenter.AppImage
        zip -r QRoboticsCenter-linux-x64.zip QRoboticsCenter.AppImage && mv QRoboticsCenter-linux-x64.zip ../
      displayName: 'pack'
    - publish: QRoboticsCenter-linux-x64.zip
      artifact: build-linux

  # BUILD for WINDOWS (Qt 5.15.1)
  - job: windows
    condition: eq(variables.WINDOWS, true)
    pool:
      vmImage: 'vs2017-win2016'
    variables:
      target: 'release' # default target
    steps:
    - script: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install aqtinstall
        python -m aqt install --outputdir $(Build.SourcesDirectory) $(QT_VERSION) windows desktop win64_mingw81
      displayName: 'setup'
    - script: |
        set PATH=$(Build.SourcesDirectory)\Qt\$(QT_VERSION)\mingw81_64\bin;%PATH
        mkdir build & cd build
        qmake.exe ../src/QRoboticsCenter/QRoboticsCenter.pro
        set CL=/MP
        nmake debug
      displayName: 'build (debug)'
      condition: not(contains(variables['Build.SourceBranch'], 'refs/tags/v')) # build with debug output unless it's a v* tag
    - script: |
        set PATH=$(Build.SourcesDirectory)\Qt\$(QT_VERSION)\mingw81_64\bin;%PATH%
        mkdir build & cd build
        qmake.exe ../src/QRoboticsCenter/QRoboticsCenter.pro
        set CL=/MP
        nmake
      displayName: 'build (release)'
      condition: contains(variables['Build.SourceBranch'], 'refs/tags/v') # build release if it's a v* tag
    - script: |
        set PATH=$(Build.SourcesDirectory)\Qt\$(QT_VERSION)\mingw81_64\bin;%PATH%
        cd build && mkdir "windows-x64"
        cp "bin/QRoboticsCenter.exe" "windows-x64/QRoboticsCenter.exe"
        windeployqt --dir "windows-x64/" "windows-x64/QRoboticsCenter.exe"
        cp "$(Build.SourcesDirectory)\Qt\$(QT_VERSION)\mingw81_64\bin\libgcc_s_seh-1.dll" "windows-x64/libgcc_s_seh-1.dll"
        cp "$(Build.SourcesDirectory)\Qt\$(QT_VERSION)\mingw81_64\bin\libstdc++-6.dll" "windows-x64/libstdc++-6"
        cp "$(Build.SourcesDirectory)\Qt\$(QT_VERSION)\mingw81_64\bin\libwinpthread-1.dll" "windows-x64/libwinpthread-1.dll"
        7z a -tzip "QRoboticsCenter-windows-x64.zip" "./windows-x64/*"
        mv "QRoboticsCenter-windows-x64.zip" ..
      displayName: 'pack'
    - publish: QRoboticsCenter-windows-x64.zip
      artifact: build-windows

  # BUILD for MAC (Qt 5.15.1)
  - job: mac
    condition: eq(variables.MAC, true)
    pool:
      vmImage: 'macOS-10.14'
    variables:
      target: 'release' # default target
    steps:
    - script: |
        brew install zip
        brew link --force zip
        curl -O https://raw.githubusercontent.com/Homebrew/homebrew-core/1dd9e85a5519c6485b536c9741a5180354e6c859/Formula/qt.rb
        brew install ./qt.rb
        brew link --force qt
      displayName: 'setup'
    - script: echo "##vso[task.setvariable variable=target;]debug"
      condition: not(contains(variables['Build.SourceBranch'], 'refs/tags/v')) # build with debug output unless it's a v* tag
    - script: |
        rm -rf build/ && mkdir build && cd build
        qmake ../src/QRoboticsCenter/QRoboticsCenter.pro
        if [ $(target) = 'debug' ]; then make debug -j5; else make -j5; fi
      displayName: 'build'
    - script: |
        cd build/bin/
        macdeployqt QRoboticsCenter.app -dmg
        zip -r QRoboticsCenter-mac-x64.zip QRoboticsCenter.dmg && cd ../../
        mv build/bin/QRoboticsCenter-mac-x64.zip .
      displayName: 'pack'
    - publish: QRoboticsCenter-mac-x64.zip
      artifact: build-mac

- stage: deploy
  condition: eq(variables.DEPLOY, true)
  dependsOn:
    - build
  jobs:

  # create develop-release if branch name is 'develop'
  - job: develop
    condition: eq(variables['Build.SourceBranchName'], 'develop')
    steps:
    - download: current
      artifact: build-linux
      condition: eq(variables.LINUX, true)
    - download: current
      artifact: build-windows
      condition: eq(variables.WINDOWS, true)
    - download: current
      artifact: build-mac
      condition: eq(variables.MAC, true)
    - bash: |
        pip install requests 1>/dev/null
        cd resources/scripts/
        echo "Delete pre-release of dev tag..."
        python2 github-api.py 'delete-release'
        echo "Update dev tag..."
        python2 github-api.py 'update-tag' '$(Build.SourceVersion)'
        echo "Create pre-release from dev tag..."
        python2 github-api.py 'create-develop-release'
        echo "Upload assets to pre-release..."
        python2 github-api.py 'upload-assets' 'QRoboticsCenter-linux-x64-develop' '../../../build-linux/QRoboticsCenter-linux-x64.zip'
        python2 github-api.py 'upload-assets' 'QRoboticsCenter-windows-x64-develop' '../../../build-windows/QRoboticsCenter-windows-x64.zip'
        python2 github-api.py 'upload-assets' 'QRoboticsCenter-mac-x64-develop' '../../../build-mac/QRoboticsCenter-mac-x64.zip'
      env:
        TOKEN: $(token)
        USER: $(user)
        REPO: $(repo)
        TAG: 'dev'

  # create release if branch contains 'refs/tags/v' (i.e., is tagged with 'v*')
  - job: release
    condition: contains(variables['Build.SourceBranch'], 'refs/tags/v')
    variables:
      tag: ''
    steps:
    - download: current
      artifact: build-linux
      condition: eq(variables.LINUX, true)
    - download: current
      artifact: build-windows
      condition: eq(variables.WINDOWS, true)
    - download: current
      artifact: build-mac
      condition: eq(variables.MAC, true)
    - bash: echo "##vso[task.setvariable variable=tag;]""$(git describe --tags)"
    - bash: |
        pip install requests 1>/dev/null
        cd resources/scripts/
        echo "Delete release if already exists for this tag..."
        python2 github-api.py 'delete-release'
        echo "Create release from tag..."
        python2 github-api.py 'create-release'
        echo "Upload assets to release..."
        python2 github-api.py 'upload-assets' 'QRoboticsCenter-linux-x64-$(tag)' '../../../build-linux/QRoboticsCenter-linux-x64.zip'
        python2 github-api.py 'upload-assets' 'QRoboticsCenter-windows-x64-$(tag)' '../../../build-windows/QRoboticsCenter-windows-x64.zip'
        python2 github-api.py 'upload-assets' 'QRoboticsCenter-mac-x64-$(tag)' '../../../build-mac/QRoboticsCenter-mac-x64.zip'
      env:
        TOKEN: $(token)
        USER: $(user)
        REPO: $(repo)
        TAG: $(tag)
